### ISSUE TITLE
Project history overview

### ISSUE THREAD

**Issue by frantisekrusnak** [m2ms/fragalysis-frontend#15]
As a user I want to see stored project’s sessions at the timeline.

-	Timeline has branch view
-       Every branch consists of saved snapshots
-       For every snapshots the name and creation date is displayed
-       Currently selected snapshot is marked by "Selected snapshot" tag
-       Initial snapshot is marked by "Initial snapshot" tag
-       If the project is created from scratch then the initial snapshot is automatically generated and this snapshot is tagged by "Auto generated initial snapshot"

**Comment by veronikabelusikova** [comment]
- [ ] Timeline has branch view
- [ ] Every branch consists of saved snapshots
- [ ] For every snapshots the name and creation date is displayed
- [ ] Currently selected snapshot is marked by "Selected snapshot" tag
- [ ] Initial snapshot is marked by "Initial snapshot" tag
- [ ] If the project is created from scratch then the initial snapshot is automatically generated and this snapshot is tagged by "Auto generated initial snapshot"
